#!/bin/sh
files=$(git diff --cached --name-only --diff-filter=ACMR main | grep -E '\.(cpp|hpp)$')
[ -z "$files" ] && exit 0

echo "Running clang-format on changed C++ files..."
echo "$files" | xargs clang-format -i
git add $files
